//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by nester.rc
//
#define ID_RESET                        3
#define IDI_HAPPY                       101
#define IDI_NESTERICON                  101
#define IDR_MENU1                       102
#define IDR_MAIN_ACCEL                  103
#define IDD_DIALOG1                     104
#define IDD_OPTIONS_GRAPHICS            106
#define IDD_OPTIONS_SOUND               107
#define IDD_OPTIONS_CONTROLLERS         108
#define IDD_HELP_ABOUT                  109
#define IDD_OPTIONS_PREFERENCES         110
#define IDD_ROMINFO                     113
#define IDC_BLACKANDWHITE               1000
#define IDC_DOUBLESIZE                  1001
#define IDC_SHOWSPRITES                 1003
#define IDC_SHOWALLSCANLINES            1004
#define IDC_DRAWOVERSCAN                1006
#define IDC_CALCPALETTE                 1007
#define IDC_SOUNDENABLE                 1008
#define IDC_FULLSCREENONLOAD            1008
#define IDC_FULLSCREENSCALING           1009
#define IDC_HOMEPAGE                    1012
#define IDC_SAMPLERATE                  1014
#define IDC_CONTROLLER1_TYPE            1015
#define IDC_BUFFERLEN                   1015
#define IDC_RUNINBG                     1016
#define IDC_SPEEDTHROTTLE               1017
#define IDC_BUTTON_A                    1018
#define IDC_AUTOFRAMESKIP               1018
#define IDC_BUTTON_B                    1019
#define IDC_ASSOCIATE                   1019
#define IDC_BUTTON_SELECT               1020
#define IDC_SOUND_FILTER_LOWPASS        1020
#define IDC_BUTTON_START                1021
#define IDC_BUTTON_UP                   1022
#define IDC_BUTTON_DOWN                 1023
#define IDC_SOUND_FILTER_NONE           1023
#define IDC_BUTTON_LEFT                 1024
#define IDC_SOUND_FILTER_LOWPASS_WEIGHTED 1024
#define IDC_BUTTON_RIGHT                1025
#define IDC_PRIORITY                    1025
#define IDC_TINT                        1026
#define IDC_HUE                         1027
#define IDC_UNDO                        1029
#define IDC_DEVICE                      1031
#define IDC_MODE                        1032
#define IDC_STATIC_UP                   1041
#define IDC_STATIC_DOWN                 1042
#define IDC_STATIC_LEFT                 1043
#define IDC_STATIC_RIGHT                1044
#define IDC_STATIC_SELECT               1045
#define IDC_STATIC_START                1046
#define IDC_STATIC_B                    1047
#define IDC_STATIC_A                    1048
#define IDC_UP_DEVICE                   1049
#define IDC_UP_BUTTON                   1050
#define IDC_SELECT_DEVICE               1051
#define IDC_DOWN_DEVICE                 1052
#define IDC_DOWN_BUTTON                 1053
#define IDC_LEFT_DEVICE                 1054
#define IDC_LEFT_BUTTON                 1055
#define IDC_RIGHT_DEVICE                1056
#define IDC_RIGHT_BUTTON                1057
#define IDC_SELECT_BUTTON               1058
#define IDC_START_DEVICE                1059
#define IDC_START_BUTTON                1060
#define IDC_B_DEVICE                    1061
#define IDC_B_BUTTON                    1062
#define IDC_A_DEVICE                    1063
#define IDC_A_BUTTON                    1064
#define IDC_PLAYER                      1065
#define IDC_DEFAULTS                    1066
#define IDC_CONTROLPANEL                1067
#define IDC_VERSION                     1071
#define IDC_RECTANGLE1                  1073
#define IDC_RECTANGLE2                  1074
#define IDC_TITLE                       1074
#define IDC_TRIANGLE                    1075
#define IDC_FILENAME                    1075
#define IDC_NOISE                       1076
#define IDC_MAPPERNUM                   1076
#define IDC_DPCM                        1077
#define IDC_MIRRORING                   1077
#define IDC_EXTERNAL                    1078
#define IDC_SOUND_SAMPLESIZE_8_BIT      1079
#define IDC_ROMSIZE                     1080
#define IDC_SOUND_SAMPLESIZE_16_BIT     1080
#define IDC_VROMSIZE                    1081
#define IDC_HASTRAINER                  1082
#define IDC_SAVERAM                     1083
#define IDC_SRAM_ROMDIRECTORY           1085
#define IDC_SRAM_NESTERDIRECTORY        1086
#define IDC_SRAM_EDITBOX                1087
#define IDC_SAVESTATE_ROMDIRECTORY      1088
#define IDC_SAVESTATE_NESTERDIRECTORY   1089
#define IDC_SAVESTATE_EDITBOX           1090
#define ID_FILE_OPEN_ROM                40001
#define ID_FILE_RESET                   40002
#define ID_FILE_EXIT                    40003
#define ID_OPTIONS_GRAPHICS             40004
#define ID_OPTIONS_SOUND                40005
#define ID_OPTIONS_CONTROLLERS          40006
#define ID_OPTIONS_FULLSCREEN           40007
#define ID_FILE_CLOSE_ROM               40008
#define ID_FILE_SAVE_STATE              40009
#define ID_FILE_LOAD_STATE              40010
#define ID_HELP_ABOUT                   40011
#define ID_FILE_QUICK_LOAD              40012
#define ID_FILE_QUICK_SAVE              40013
#define ID_OPTIONS_PREFERENCES          40014
#define ID_FILE_RECENT_0                40015
#define ID_FILE_RECENT_1                40016
#define ID_FILE_RECENT_2                40017
#define ID_FILE_RECENT_3                40018
#define ID_FILE_RECENT_4                40019
#define ID_FILE_RECENT_5                40020
#define ID_FILE_RECENT_6                40021
#define ID_FILE_RECENT_7                40022
#define ID_FILE_RECENT_8                40023
#define ID_FILE_RECENT_9                40024
#define ID_OPTIONS_DOUBLESIZE           40026
#define ID_FILE_SLOT_0                  40028
#define ID_FILE_SLOT_1                  40029
#define ID_FILE_SLOT_2                  40030
#define ID_FILE_SLOT_3                  40031
#define ID_FILE_SLOT_4                  40032
#define ID_FILE_SLOT_5                  40033
#define ID_FILE_SLOT_6                  40034
#define ID_FILE_SLOT_7                  40035
#define ID_FILE_SLOT_8                  40036
#define ID_FILE_SLOT_9                  40037
#define ID_FILE_ROMINFO                 40038
#define ID_FILE_PAUSE                   40039

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        114
#define _APS_NEXT_COMMAND_VALUE         40040
#define _APS_NEXT_CONTROL_VALUE         1088
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
